<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from dialfire/xml/schema/CRM/Dialfire/002-DialfireCampaign.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:ab9fb4ef509e57c85d293d9080633ece)
 */
use CRM_Dialfire_ExtensionUtil as E;

/**
 * Database access object for the DialfireCampaign entity.
 */
class CRM_Dialfire_DAO_DialfireCampaign extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_dialfire_campaign';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique DialfireCampaign ID
   *
   * @var int
   */
  public $id;

  /**
   * Unique identifier of campaign in dialfire
   *
   * @var string
   */
  public $dialfire_campaign_identifier;

  /**
   * FK to Dialfire Tenant
   *
   * @var int
   */
  public $dialfire_tenant_id;

  /**
   * Campaign name
   *
   * @var string
   */
  public $name;

  /**
   * Tenant token
   *
   * @var string
   */
  public $token;

  /**
   * Custom API4 contact query for this campaign
   *
   * @var text
   */
  public $contact_query;

  /**
   * Custom field map of JMESPath expressions for this campaign
   *
   * @var text
   */
  public $field_map;

  /**
   * @var timestamp
   */
  public $created_date;

  /**
   * @var timestamp
   */
  public $modified_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_dialfire_campaign';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Dialfire Campaigns') : E::ts('Dialfire Campaign');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'dialfire_tenant_id', 'civicrm_dialfire_tenant', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique DialfireCampaign ID'),
          'required' => TRUE,
          'where' => 'civicrm_dialfire_campaign.id',
          'table_name' => 'civicrm_dialfire_campaign',
          'entity' => 'DialfireCampaign',
          'bao' => 'CRM_Dialfire_DAO_DialfireCampaign',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'dialfire_campaign_identifier' => [
          'name' => 'dialfire_campaign_identifier',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Dialfire Campaign ID'),
          'description' => E::ts('Unique identifier of campaign in dialfire'),
          'required' => TRUE,
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_dialfire_campaign.dialfire_campaign_identifier',
          'table_name' => 'civicrm_dialfire_campaign',
          'entity' => 'DialfireCampaign',
          'bao' => 'CRM_Dialfire_DAO_DialfireCampaign',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'dialfire_tenant_id' => [
          'name' => 'dialfire_tenant_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Dialfire Tenant'),
          'where' => 'civicrm_dialfire_campaign.dialfire_tenant_id',
          'table_name' => 'civicrm_dialfire_campaign',
          'entity' => 'DialfireCampaign',
          'bao' => 'CRM_Dialfire_DAO_DialfireCampaign',
          'localizable' => 0,
          'FKClassName' => 'CRM_Dialfire_DAO_DialfireTenant',
          'html' => [
            'type' => 'Select',
          ],
          'add' => NULL,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Campaign Name'),
          'description' => E::ts('Campaign name'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_dialfire_campaign.name',
          'table_name' => 'civicrm_dialfire_campaign',
          'entity' => 'DialfireCampaign',
          'bao' => 'CRM_Dialfire_DAO_DialfireCampaign',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'token' => [
          'name' => 'token',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Token'),
          'description' => E::ts('Tenant token'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_dialfire_campaign.token',
          'table_name' => 'civicrm_dialfire_campaign',
          'entity' => 'DialfireCampaign',
          'bao' => 'CRM_Dialfire_DAO_DialfireCampaign',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'contact_query' => [
          'name' => 'contact_query',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Contact Query (JSON)'),
          'description' => E::ts('Custom API4 contact query for this campaign'),
          'where' => 'civicrm_dialfire_campaign.contact_query',
          'table_name' => 'civicrm_dialfire_campaign',
          'entity' => 'DialfireCampaign',
          'bao' => 'CRM_Dialfire_DAO_DialfireCampaign',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'field_map' => [
          'name' => 'field_map',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Field Map (JSON)'),
          'description' => E::ts('Custom field map of JMESPath expressions for this campaign'),
          'where' => 'civicrm_dialfire_campaign.field_map',
          'table_name' => 'civicrm_dialfire_campaign',
          'entity' => 'DialfireCampaign',
          'bao' => 'CRM_Dialfire_DAO_DialfireCampaign',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created Date'),
          'required' => TRUE,
          'where' => 'civicrm_dialfire_campaign.created_date',
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_dialfire_campaign',
          'entity' => 'DialfireCampaign',
          'bao' => 'CRM_Dialfire_DAO_DialfireCampaign',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Modified Date'),
          'where' => 'civicrm_dialfire_campaign.modified_date',
          'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_dialfire_campaign',
          'entity' => 'DialfireCampaign',
          'bao' => 'CRM_Dialfire_DAO_DialfireCampaign',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'dialfire_campaign', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'dialfire_campaign', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_dialfire_campaign_identifier' => [
        'name' => 'UI_dialfire_campaign_identifier',
        'field' => [
          0 => 'dialfire_campaign_identifier',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_dialfire_campaign::1::dialfire_campaign_identifier',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
