<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from dialfire/xml/schema/CRM/Dialfire/001-DialfireTenant.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:a03d05ab0755ed33a0e20effb41a0080)
 */
use CRM_Dialfire_ExtensionUtil as E;

/**
 * Database access object for the DialfireTenant entity.
 */
class CRM_Dialfire_DAO_DialfireTenant extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_dialfire_tenant';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique DialfireTenant ID
   *
   * @var int
   */
  public $id;

  /**
   * Unique identifier of tenant in dialfire
   *
   * @var string
   */
  public $dialfire_tenant_identifier;

  /**
   * Tenant name
   *
   * @var string
   */
  public $name;

  /**
   * Tenant token
   *
   * @var string
   */
  public $token;

  /**
   * @var timestamp
   */
  public $created_date;

  /**
   * @var timestamp
   */
  public $modified_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_dialfire_tenant';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Dialfire Tenants') : E::ts('Dialfire Tenant');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique DialfireTenant ID'),
          'required' => TRUE,
          'where' => 'civicrm_dialfire_tenant.id',
          'table_name' => 'civicrm_dialfire_tenant',
          'entity' => 'DialfireTenant',
          'bao' => 'CRM_Dialfire_DAO_DialfireTenant',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'dialfire_tenant_identifier' => [
          'name' => 'dialfire_tenant_identifier',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Dialfire Tenant ID'),
          'description' => E::ts('Unique identifier of tenant in dialfire'),
          'required' => TRUE,
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_dialfire_tenant.dialfire_tenant_identifier',
          'table_name' => 'civicrm_dialfire_tenant',
          'entity' => 'DialfireTenant',
          'bao' => 'CRM_Dialfire_DAO_DialfireTenant',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Tenant Name'),
          'description' => E::ts('Tenant name'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_dialfire_tenant.name',
          'table_name' => 'civicrm_dialfire_tenant',
          'entity' => 'DialfireTenant',
          'bao' => 'CRM_Dialfire_DAO_DialfireTenant',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'token' => [
          'name' => 'token',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Token'),
          'description' => E::ts('Tenant token'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_dialfire_tenant.token',
          'table_name' => 'civicrm_dialfire_tenant',
          'entity' => 'DialfireTenant',
          'bao' => 'CRM_Dialfire_DAO_DialfireTenant',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created Date'),
          'required' => TRUE,
          'where' => 'civicrm_dialfire_tenant.created_date',
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_dialfire_tenant',
          'entity' => 'DialfireTenant',
          'bao' => 'CRM_Dialfire_DAO_DialfireTenant',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Modified Date'),
          'where' => 'civicrm_dialfire_tenant.modified_date',
          'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_dialfire_tenant',
          'entity' => 'DialfireTenant',
          'bao' => 'CRM_Dialfire_DAO_DialfireTenant',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'dialfire_tenant', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'dialfire_tenant', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_dialfire_tenant_identifier' => [
        'name' => 'UI_dialfire_tenant_identifier',
        'field' => [
          0 => 'dialfire_tenant_identifier',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_dialfire_tenant::1::dialfire_tenant_identifier',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
