<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from dialfire/xml/schema/CRM/Dialfire/004-DialfireContact.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:cb7c7a7db7b9b6fe944e2c76950a7339)
 */
use CRM_Dialfire_ExtensionUtil as E;

/**
 * Database access object for the DialfireContact entity.
 */
class CRM_Dialfire_DAO_DialfireContact extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_dialfire_contact';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique DialfireContact ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Dialfire Task
   *
   * @var int
   */
  public $dialfire_task_id;

  /**
   * FK to Contact
   *
   * @var int
   */
  public $contact_id;

  /**
   * Unique identifier of contact in dialfire
   *
   * @var string
   */
  public $dialfire_contact_identifier;

  /**
   * Last synchronized version of the record in dialfire
   *
   * @var string
   */
  public $dialfire_record_version;

  /**
   * FK to Activity
   *
   * @var int
   */
  public $activity_id;

  /**
   * @var text
   */
  public $custom_data;

  /**
   * @var text
   */
  public $last_payload;

  /**
   * @var longtext
   */
  public $last_error;

  /**
   * Number of consecutive synchronization errors
   *
   * @var int
   */
  public $error_count;

  /**
   * ID of synchronization status
   *
   * @var int
   */
  public $synchronization_status_id;

  /**
   * Date of last synchronization
   *
   * @var timestamp
   */
  public $synchronization_date;

  /**
   * @var timestamp
   */
  public $created_date;

  /**
   * @var timestamp
   */
  public $modified_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_dialfire_contact';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Dialfire Contacts') : E::ts('Dialfire Contact');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'dialfire_task_id', 'civicrm_dialfire_task', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'activity_id', 'civicrm_activity', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique DialfireContact ID'),
          'required' => TRUE,
          'where' => 'civicrm_dialfire_contact.id',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'dialfire_task_id' => [
          'name' => 'dialfire_task_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Dialfire Task'),
          'where' => 'civicrm_dialfire_contact.dialfire_task_id',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'FKClassName' => 'CRM_Dialfire_DAO_DialfireTask',
          'html' => [
            'type' => 'Select',
          ],
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Contact'),
          'required' => TRUE,
          'where' => 'civicrm_dialfire_contact.contact_id',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'dialfire_contact_identifier' => [
          'name' => 'dialfire_contact_identifier',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Dialfire Contact ID'),
          'description' => E::ts('Unique identifier of contact in dialfire'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_dialfire_contact.dialfire_contact_identifier',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'dialfire_record_version' => [
          'name' => 'dialfire_record_version',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Dialfire Record Version'),
          'description' => E::ts('Last synchronized version of the record in dialfire'),
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_dialfire_contact.dialfire_record_version',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'activity_id' => [
          'name' => 'activity_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Activity'),
          'where' => 'civicrm_dialfire_contact.activity_id',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'FKClassName' => 'CRM_Activity_DAO_Activity',
          'add' => NULL,
        ],
        'custom_data' => [
          'name' => 'custom_data',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Custom Data (JSON)'),
          'where' => 'civicrm_dialfire_contact.custom_data',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'last_payload' => [
          'name' => 'last_payload',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Last Payload (JSON)'),
          'where' => 'civicrm_dialfire_contact.last_payload',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'last_error' => [
          'name' => 'last_error',
          'type' => CRM_Utils_Type::T_LONGTEXT,
          'title' => E::ts('Last Error (JSON)'),
          'where' => 'civicrm_dialfire_contact.last_error',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'error_count' => [
          'name' => 'error_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Consecutive Synchronization Error Count'),
          'description' => E::ts('Number of consecutive synchronization errors'),
          'required' => TRUE,
          'where' => 'civicrm_dialfire_contact.error_count',
          'default' => '0',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'synchronization_status_id' => [
          'name' => 'synchronization_status_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Synchronization Status'),
          'description' => E::ts('ID of synchronization status'),
          'required' => TRUE,
          'where' => 'civicrm_dialfire_contact.synchronization_status_id',
          'default' => '1',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'dialfire_synchronization_status',
            'optionEditPath' => 'civicrm/admin/options/dialfire_synchronization_status',
          ],
          'add' => NULL,
        ],
        'synchronization_date' => [
          'name' => 'synchronization_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Synchronization Date'),
          'description' => E::ts('Date of last synchronization'),
          'where' => 'civicrm_dialfire_contact.synchronization_date',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created Date'),
          'required' => TRUE,
          'where' => 'civicrm_dialfire_contact.created_date',
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Modified Date'),
          'where' => 'civicrm_dialfire_contact.modified_date',
          'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_dialfire_contact',
          'entity' => 'DialfireContact',
          'bao' => 'CRM_Dialfire_DAO_DialfireContact',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'dialfire_contact', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'dialfire_contact', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
