<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from dialfire/xml/schema/CRM/Dialfire/003-DialfireTask.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:16dbe32506665552d8b1a6cd915f6b0b)
 */
use CRM_Dialfire_ExtensionUtil as E;

/**
 * Database access object for the DialfireTask entity.
 */
class CRM_Dialfire_DAO_DialfireTask extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_dialfire_task';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique DialfireTask ID
   *
   * @var int
   */
  public $id;

  /**
   * Unique identifier of task in dialfire
   *
   * @var string
   */
  public $dialfire_task_identifier;

  /**
   * FK to Dialfire Campaign
   *
   * @var int
   */
  public $dialfire_campaign_id;

  /**
   * Task name
   *
   * @var string
   */
  public $name;

  /**
   * @var timestamp
   */
  public $created_date;

  /**
   * @var timestamp
   */
  public $modified_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_dialfire_task';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Dialfire Tasks') : E::ts('Dialfire Task');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'dialfire_campaign_id', 'civicrm_dialfire_campaign', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique DialfireTask ID'),
          'required' => TRUE,
          'where' => 'civicrm_dialfire_task.id',
          'table_name' => 'civicrm_dialfire_task',
          'entity' => 'DialfireTask',
          'bao' => 'CRM_Dialfire_DAO_DialfireTask',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'dialfire_task_identifier' => [
          'name' => 'dialfire_task_identifier',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Dialfire Task ID'),
          'description' => E::ts('Unique identifier of task in dialfire'),
          'required' => TRUE,
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_dialfire_task.dialfire_task_identifier',
          'table_name' => 'civicrm_dialfire_task',
          'entity' => 'DialfireTask',
          'bao' => 'CRM_Dialfire_DAO_DialfireTask',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'dialfire_campaign_id' => [
          'name' => 'dialfire_campaign_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Dialfire Campaign'),
          'where' => 'civicrm_dialfire_task.dialfire_campaign_id',
          'table_name' => 'civicrm_dialfire_task',
          'entity' => 'DialfireTask',
          'bao' => 'CRM_Dialfire_DAO_DialfireTask',
          'localizable' => 0,
          'FKClassName' => 'CRM_Dialfire_DAO_DialfireCampaign',
          'html' => [
            'type' => 'Select',
          ],
          'add' => NULL,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Task Name'),
          'description' => E::ts('Task name'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_dialfire_task.name',
          'table_name' => 'civicrm_dialfire_task',
          'entity' => 'DialfireTask',
          'bao' => 'CRM_Dialfire_DAO_DialfireTask',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created Date'),
          'required' => TRUE,
          'where' => 'civicrm_dialfire_task.created_date',
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_dialfire_task',
          'entity' => 'DialfireTask',
          'bao' => 'CRM_Dialfire_DAO_DialfireTask',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Modified Date'),
          'where' => 'civicrm_dialfire_task.modified_date',
          'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_dialfire_task',
          'entity' => 'DialfireTask',
          'bao' => 'CRM_Dialfire_DAO_DialfireTask',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'dialfire_task', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'dialfire_task', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_dialfire_task_identifier_dialfire_campaign_id' => [
        'name' => 'UI_dialfire_task_identifier_dialfire_campaign_id',
        'field' => [
          0 => 'dialfire_task_identifier',
          1 => 'dialfire_campaign_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_dialfire_task::1::dialfire_task_identifier::dialfire_campaign_id',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
