-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_dialfire_response`;
DROP TABLE IF EXISTS `civicrm_dialfire_contact`;
DROP TABLE IF EXISTS `civicrm_dialfire_task`;
DROP TABLE IF EXISTS `civicrm_dialfire_campaign`;
DROP TABLE IF EXISTS `civicrm_dialfire_tenant`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_dialfire_tenant
-- *
-- *******************************************************/
CREATE TABLE `civicrm_dialfire_tenant` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique DialfireTenant ID',
  `dialfire_tenant_identifier` varchar(64) NOT NULL COMMENT 'Unique identifier of tenant in dialfire',
  `name` varchar(255) NOT NULL COMMENT 'Tenant name',
  `token` varchar(255) NOT NULL COMMENT 'Tenant token',
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_dialfire_tenant_identifier`(dialfire_tenant_identifier)
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_dialfire_campaign
-- *
-- *******************************************************/
CREATE TABLE `civicrm_dialfire_campaign` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique DialfireCampaign ID',
  `dialfire_campaign_identifier` varchar(64) NOT NULL COMMENT 'Unique identifier of campaign in dialfire',
  `dialfire_tenant_id` int unsigned COMMENT 'FK to Dialfire Tenant',
  `name` varchar(255) NOT NULL COMMENT 'Campaign name',
  `token` varchar(255) NOT NULL COMMENT 'Tenant token',
  `contact_query` text COMMENT 'Custom API4 contact query for this campaign',
  `field_map` text COMMENT 'Custom field map of JMESPath expressions for this campaign',
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_dialfire_campaign_identifier`(dialfire_campaign_identifier),
  CONSTRAINT FK_civicrm_dialfire_campaign_dialfire_tenant_id FOREIGN KEY (`dialfire_tenant_id`) REFERENCES `civicrm_dialfire_tenant`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_dialfire_task
-- *
-- *******************************************************/
CREATE TABLE `civicrm_dialfire_task` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique DialfireTask ID',
  `dialfire_task_identifier` varchar(64) NOT NULL COMMENT 'Unique identifier of task in dialfire',
  `dialfire_campaign_id` int unsigned COMMENT 'FK to Dialfire Campaign',
  `name` varchar(255) NULL COMMENT 'Task name',
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_dialfire_task_identifier_dialfire_campaign_id`(dialfire_task_identifier, dialfire_campaign_id),
  CONSTRAINT FK_civicrm_dialfire_task_dialfire_campaign_id FOREIGN KEY (`dialfire_campaign_id`) REFERENCES `civicrm_dialfire_campaign`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_dialfire_contact
-- *
-- *******************************************************/
CREATE TABLE `civicrm_dialfire_contact` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique DialfireContact ID',
  `dialfire_task_id` int unsigned COMMENT 'FK to Dialfire Task',
  `contact_id` int unsigned NOT NULL COMMENT 'FK to Contact',
  `dialfire_contact_identifier` varchar(64) COMMENT 'Unique identifier of contact in dialfire',
  `dialfire_record_version` varchar(64) COMMENT 'Last synchronized version of the record in dialfire',
  `activity_id` int unsigned COMMENT 'FK to Activity',
  `custom_data` text,
  `last_payload` text,
  `last_error` longtext,
  `error_count` tinyint NOT NULL DEFAULT 0 COMMENT 'Number of consecutive synchronization errors',
  `synchronization_status_id` int unsigned NOT NULL DEFAULT 1 COMMENT 'ID of synchronization status',
  `synchronization_date` timestamp COMMENT 'Date of last synchronization',
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_dialfire_contact_dialfire_task_id FOREIGN KEY (`dialfire_task_id`) REFERENCES `civicrm_dialfire_task`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_dialfire_contact_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_dialfire_contact_activity_id FOREIGN KEY (`activity_id`) REFERENCES `civicrm_activity`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_dialfire_response
-- *
-- *******************************************************/
CREATE TABLE `civicrm_dialfire_response` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique DialfireResponse ID',
  `dialfire_task_id` int unsigned COMMENT 'FK to Dialfire Task',
  `dialfire_contact_id` int unsigned COMMENT 'FK to DialfireContact',
  `dialfire_contact_identifier` varchar(64) NOT NULL COMMENT 'Unique identifier of contact in dialfire',
  `dialfire_record_version` varchar(64) NOT NULL COMMENT 'Current version of the record in dialfire',
  `dialfire_entry_date` timestamp NOT NULL COMMENT 'Date of last status change in dialfire',
  `response` text NOT NULL,
  `last_error` longtext,
  `response_status_id` int unsigned NOT NULL DEFAULT 1 COMMENT 'ID of response status',
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_dialfire_response_dialfire_task_id FOREIGN KEY (`dialfire_task_id`) REFERENCES `civicrm_dialfire_task`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_dialfire_response_dialfire_contact_id FOREIGN KEY (`dialfire_contact_id`) REFERENCES `civicrm_dialfire_contact`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;
